platform :ios, '8.0'

use_frameworks!

target 'Demo' do
  pod 'SDWebImage'
  pod 'YCSymbolTracker', :path => '../'
end

post_install do |installer|
    require '../YCSymbolTracker/symbol_tracker.rb'
    symbol_tracker(installer)
end
